version: '3'

services:

  load_balancer:
    image: nginx:1.19.6
    container_name: load_balancer
    ports:
    - "80:80"
    volumes:
    - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
    - backend_container
    command: ["nginx", "-g", "daemon off;"]
    networks:
    - practica_net

  prometheus_practica:
    image: prom/prometheus:v2.20.1
    container_name: prometheus_practica
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
    - backend_container
    networks:
    - practica_net

  grafana_practica:
    image: grafana/grafana:7.1.5
    container_name: grafana_practica
    ports:
    - "3500:3000"
    volumes:
    - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    - myGrafanaVol:/var/lib/grafana
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: ${GF_AUTH_DISABLE_LOGIN_FORM}
      GF_AUTH_ANONYMOUS_ENABLED: ${GF_AUTH_ANONYMOUS_ENABLED}
      GF_AUTH_ANONYMOUS_ORG_ROLE: ${GF_AUTH_ANONYMOUS_ORG_ROLE}
      GF_INSTALL_PLUGINS: ${GF_INSTALL_PLUGINS}
    depends_on:
    - prometheus_practica
    networks:
    - practica_net

  frontend_container:
    image: node:19-alpine
    container_name: frontend_container
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
     - 1233:1233
    volumes:
      - ./frontend:/app
    depends_on:
      - backend_container
    networks:
      - practica_net

  backend_container:
    image: node:19-alpine
    container_name: backend_container
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
     - 1234:1234
    volumes:
      - ./backend:/app
    depends_on:
      - mongo-container
      - adminMongo-container
    networks:
      - practica_net

  adminMongo-container:
    image: mongo-express:latest
    container_name: adminMongo-container
    restart: unless-stopped
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo-container
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_MONGODB_URL}
    depends_on:
      mongo-container:
        condition: service_healthy
    networks:
      - practica_net

  mongo-container:
    image: mongo:latest
    container_name: mongo-container
    restart: always
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
    hostname: mongo-container
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1/mongo-container",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo/mongodump.sh:/docker-entrypoint-initdb.d/mongodump.sh:ro
      - ./mongo/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./mongo/db-dump:/db-dump
    networks:
      - practica_net
  
networks:
  practica_net:

volumes:
  myGrafanaVol: